services:
#name of the postgres container
 postgres:
       #image to make ccntainer
        image: docker.io/postgres
        #env variables
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api

 api:
        build:
            context: ./
            dockerfile: Dockerfile
        image: docker.io/sreesiri2docker/simple_blog_api

        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api

        ports:
          - "3000:3000"
